services:
  companies-external-api:
    build:
      context: .
      dockerfile: src/Companies.External.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
    networks:
      - grpc-network

  companies-api:
    build:
      context: .
      dockerfile: src/Companies.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - companies-external-api
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge
