services:
  companies-external-api:
    build:
      context: .
      dockerfile: src/Companies.External.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - grpc-network

  companies-api:
    build:
      context: .
      dockerfile: src/Companies.Api/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - companies-external-api
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge
